controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - fr_steering_joint
      - fl_steering_joint
      - rr_wheel_joint
      - rl_wheel_joint

forward_velocity_controller:
  ros__parameters:
    joints:
      - rr_wheel_joint
      - rl_wheel_joint
    interface_name: velocity

forward_position_controller:
  ros__parameters:
    joints:
      - fr_steering_joint
      - fl_steering_joint
    interface_name: position
